# Generated by Django 5.0.3 on 2024-08-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
