# Generated by Django 5.0.3 on 2024-08-26 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
