# Generated by Django 5.0.3 on 2024-08-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting_app', '0002_rename_content_post_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Terms',
        ),
    ]
