# Generated by Django 5.0.3 on 2024-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_ref_no',
            field=models.UUIDField(editable=False, verbose_name='Reference Number'),
        ),
    ]
