# Generated by Django 5.0.3 on 2024-08-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0002_alter_transaction_transaction_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_ref_no',
            field=models.CharField(editable=False, max_length=20, verbose_name='Reference Number'),
        ),
    ]
