# Generated by Django 5.0.3 on 2024-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0004_alter_transaction_transaction_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
