# Generated by Django 5.0.3 on 2024-08-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_ref_no',
            field=models.CharField(max_length=50, verbose_name='Reference Number'),
        ),
    ]
