# Generated by Django 5.0.3 on 2024-08-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0006_alter_transaction_transaction_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=50),
        ),
    ]
