# Generated by Django 5.0.3 on 2024-08-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='new_bal',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
