# Generated by Django 5.0.3 on 2024-08-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0008_transaction_new_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
