# Generated by Django 5.0.3 on 2024-12-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_alter_user_email_alter_wallet_balance_fundingdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="reference",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
